version: '3'
services:
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - '3000:3000'
volumes:
  node_modules:
